<a href="https://colab.research.google.com/github/Anubhavkumar076/ai_data_analysis/blob/main/Movie%20Case%20Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = [1, 2, 3, 4, 5]
arr

[1, 2, 3, 4, 5]

In [ ]:
np_arr = np.array(arr)
np_arr
print(np_arr)

[1 2 3 4 5]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
arr = np.arange(1, 5, 1).reshape(2, 2)
arr1 = arr.T
print(arr)
print(arr1)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
random_num = np.random.randint(10, 20, (10, 10))
print(random_num)

[[11 15 19 15 17 18 16 13 18 11]
 [19 17 17 17 14 19 15 12 15 16]
 [15 13 10 19 16 19 18 15 12 15]
 [19 11 11 10 17 19 18 16 18 15]
 [14 18 10 11 10 19 16 17 18 15]
 [11 14 14 18 11 17 18 18 12 12]
 [13 18 14 11 19 12 11 17 11 16]
 [15 16 11 19 17 15 13 16 14 16]
 [15 13 11 15 11 15 13 15 10 12]
 [17 11 16 11 12 13 19 14 15 10]]


In [ ]:
rand_num2 = np.random.randn(1, 4)
print(rand_num2)

[[ 1.05129134 -0.19960075 -1.05482426  0.7843036 ]]


In [ ]:
import numpy as np
import pandas as pd

movie = pd.read_csv("movie.csv")
ratings = pd.read_csv("ratings.csv")
user = pd.read_csv("user.csv")

ratings.head(5)

,user id,movie id,rating,timestamp
0,196,242,3,881250949
1,186,302,3,891717742
2,22,377,1,878887116
3,244,51,2,880606923
4,166,346,1,886397596


In [ ]:
print(user.shape)
print(ratings.shape)
print(movie.shape)

(943, 5)
(100000, 4)
(1680, 21)


In [ ]:
print(user.info())
print(ratings.info())
print(movie.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   user id     943 non-null    int64 
 1   age         943 non-null    int64 
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user id    100000 non-null  int64
 1   movie id   100000 non-null  int64
 2   rating     100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        ------

In [ ]:
movie.describe()

,movie id,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
count,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000
mean,841.525595,0.149405,0.080357,0.025000,0.072619,0.300595,0.064881,0.029762,0.431548,0.013095,0.014286,0.054762,0.033333,0.036310,0.147024,0.060119,0.149405,0.042262,0.016071
std,485.609591,0.356593,0.271926,0.156171,0.259587,0.458653,0.246389,0.169980,0.495440,0.113717,0.118701,0.227583,0.179559,0.187115,0.354235,0.237778,0.356593,0.201246,0.125788
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,421.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,841.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1261.250000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1682.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000


In [ ]:
ratings.describe()

,user id,movie id,rating,timestamp
count,100000.00000,100000.000000,100000.000000,1.000000e+05
mean,462.48475,425.530130,3.529860,8.835289e+08
std,266.61442,330.798356,1.125674,5.343856e+06
min,1.00000,1.000000,1.000000,8.747247e+08
25%,254.00000,175.000000,3.000000,8.794487e+08
50%,447.00000,322.000000,4.000000,8.828269e+08
75%,682.00000,631.000000,4.000000,8.882600e+08
max,943.00000,1682.000000,5.000000,8.932866e+08


# How many movies belong to particular genre

In [ ]:
movie.columns

Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [ ]:
genres = ['Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western']

In [ ]:
movie[genres].sum()

,0
Action,251
Adventure,135
Animation,42
Childrens,122
Comedy,505
Crime,109
Documentary,50
Drama,725
Fantasy,22
Film-Noir,24


In [ ]:
movie[genres].sum().sort_values()

,0
Fantasy,22
Film-Noir,24
Western,27
Animation,42
Documentary,50
Musical,56
Mystery,61
War,71
Horror,92
Sci-Fi,101


# Movies that have more than one genre

In [ ]:
movie.head().loc[:, genres] #: (colon) in row_indexer: When you see just a colon (:), it means "select all rows." So, loc[:, ...] is telling pandas to consider all rows in the movie.head()

,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0


In [ ]:
movie["Number of Genres"] = movie.loc[:, genres].sum(axis=1)
movie.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,3
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,3
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,3


In [ ]:
movie[movie["Number of Genres"]>1].tail()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres
1666,1669,MURDER and murder,20-Jun-97,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,3
1667,1670,Tainted,1-Feb-98,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,2
1670,1673,Mirage,1-Jan-95,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
1676,1679,B. Monkey,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,2
1677,1680,Sliding Doors,1-Jan-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2


In [ ]:
movie[movie["Number of Genres"]>1].shape

(849, 22)

In [ ]:
movie["Number of Genres"] = movie.loc[:, genres].sum(axis=1)

In [ ]:
movie["Number of Genres"] = movie.iloc[:, 3:].sum(axis=1)

Changes to display only the ID, title, release date, and number of genres in the movies in the dataset.

In [ ]:
movie.loc[:, ['movie id', 'movie title', 'release date', 'Number of Genres']]

,movie id,movie title,release date,Number of Genres
0,1,Toy Story,1-Jan-95,6
1,2,GoldenEye,1-Jan-95,6
2,3,Four Rooms,1-Jan-95,2
3,4,Get Shorty,1-Jan-95,6
4,5,Copycat,1-Jan-95,6
...,...,...,...,...
1675,1678,Mat' i syn,6-Feb-98,2
1676,1679,B. Monkey,6-Feb-98,4
1677,1680,Sliding Doors,1-Jan-98,4
1678,1681,You So Crazy,1-Jan-94,2


In [ ]:
movie.iloc[:, [0, 1, 2, -1]]

,movie id,movie title,release date,Number of Genres
0,1,Toy Story,1-Jan-95,6
1,2,GoldenEye,1-Jan-95,6
2,3,Four Rooms,1-Jan-95,2
3,4,Get Shorty,1-Jan-95,6
4,5,Copycat,1-Jan-95,6
...,...,...,...,...
1675,1678,Mat' i syn,6-Feb-98,2
1676,1679,B. Monkey,6-Feb-98,4
1677,1680,Sliding Doors,1-Jan-98,4
1678,1681,You So Crazy,1-Jan-94,2


# Genres that are most liked by the users

In [ ]:
df_merge = movie.merge(ratings, on = "movie id", how= "inner")

In [ ]:
df_merge.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres,user id,rating,timestamp
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,308,4,887736532
1,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,287,5,875334088
2,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,148,4,877019411
3,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,280,4,891700426
4,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,66,3,883601324


In [ ]:
df_merge[df_merge["rating"]>3]

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres,user id,rating,timestamp
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,308,4,887736532
1,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,287,5,875334088
2,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,148,4,877019411
3,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,280,4,891700426
5,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,6,5,4,875635748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99965,1662,Rough Magic,30-May-97,0,0,0,0,0,0,0,...,0,1,0,0,0,0,4,782,4,891500110
99968,1664,8 Heads in a Duffel Bag,18-Apr-97,0,0,0,0,1,0,0,...,0,0,0,0,0,0,2,880,4,892958799
99969,1664,8 Heads in a Duffel Bag,18-Apr-97,0,0,0,0,1,0,0,...,0,0,0,0,0,0,2,782,4,891499699
99970,1664,8 Heads in a Duffel Bag,18-Apr-97,0,0,0,0,1,0,0,...,0,0,0,0,0,0,2,870,4,890057322


In [ ]:
for genre in genres:
  print(genre, df_merge[df_merge[genre]==1].rating.mean())

Action 3.480245417953027
Adventure 3.503526503308369
Animation 3.5766990291262135
Childrens 3.3532442216652742
Comedy 3.3940734781442745
Crime 3.6322780881440098
Documentary 3.6728232189973613
Drama 3.6873793708484772
Fantasy 3.2152366863905324
Film-Noir 3.9215233698788228
Horror 3.2903893172841827
Musical 3.521396851029471
Mystery 3.63813155386082
Romance 3.621704948358255
Sci-Fi 3.5607227022780834
Thriller 3.5090069495245064
War 3.815811874866993
Western 3.6132686084142396


# Movie with their average rating

In [ ]:
avg_rating = df_merge.groupby(['movie title'])['rating'].mean().reset_index() # reset_index will reset the index of dataframe to default indexing (0 to number of rows minus 1)
avg_rating

,movie title,rating
0,'Til There Was You,2.333333
1,1-900,2.600000
2,101 Dalmatians,2.908257
3,12 Angry Men,4.344000
4,187,3.024390
...,...,...
1652,Young Guns,3.207921
1653,Young Guns II,2.772727
1654,"Young Poisoner's Handbook, The",3.341463
1655,Zeus and Roxanne,2.166667


In [ ]:
avg_rating.rename(columns={'rating':'Avg_rating'},inplace=True)
avg_rating.head()

,movie title,Avg_rating
0,'Til There Was You,2.333333
1,1-900,2.600000
2,101 Dalmatians,2.908257
3,12 Angry Men,4.344000
4,187,3.024390


In [ ]:
avg_rating.sort_values('Avg_rating',ascending=False)

,movie title,Avg_rating
30,Aiqing wansui,5.0
1170,Prefontaine,5.0
631,"Great Day in Harlem, A",5.0
1354,Someone Else's America,5.0
1382,Star Kid,5.0
...,...,...
482,"Eye of Vichy, The (Oeil de Vichy, L')",1.0
1604,Wend Kuuni (God's Gift),1.0
1648,Yankee Zulu,1.0
1640,"Woman in Question, The",1.0


In [ ]:
avg_rating[avg_rating["Avg_rating"]==5]

,movie title,Avg_rating
30,Aiqing wansui,5.0
461,Entertaining Angels: The Dorothy Day Story,5.0
631,"Great Day in Harlem, A",5.0
942,Marlene Dietrich: Shadow and Light (,5.0
1170,Prefontaine,5.0
1270,"Saint of Fort Washington, The",5.0
1274,Santa with Muscles,5.0
1354,Someone Else's America,5.0
1382,Star Kid,5.0
1466,They Made Me a Criminal,5.0


# which movies are rated most of the times?

In [ ]:
movie_count = df_merge.groupby('movie title')['rating'].count().reset_index()
movie_count

,movie title,rating
0,'Til There Was You,9
1,1-900,5
2,101 Dalmatians,109
3,12 Angry Men,125
4,187,41
...,...,...
1652,Young Guns,101
1653,Young Guns II,44
1654,"Young Poisoner's Handbook, The",41
1655,Zeus and Roxanne,6


In [ ]:
movie_count.sort_values('rating',ascending=False, inplace=True)
movie_count

,movie title,rating
1393,Star Wars,583
332,Contact,509
497,Fargo,508
1232,Return of the Jedi,507
858,Liar Liar,485
...,...,...
1576,"Very Natural Thing, A",1
1587,"Walk in the Sun, A",1
1088,Office Killer,1
1123,Paris Was a Woman,1


In [ ]:
movie_count.rename(columns={'rating': 'Rating Counts'}, inplace=True)
movie_count

,movie title,Rating Counts
1393,Star Wars,583
332,Contact,509
497,Fargo,508
1232,Return of the Jedi,507
858,Liar Liar,485
...,...,...
1576,"Very Natural Thing, A",1
1587,"Walk in the Sun, A",1
1088,Office Killer,1
1123,Paris Was a Woman,1


In [ ]:
movie_count100 = movie_count[movie_count['Rating Counts'] > 100]
movie_count100

,movie title,Rating Counts
1393,Star Wars,583
332,Contact,509
497,Fargo,508
1232,Return of the Jedi,507
858,Liar Liar,485
...,...,...
1652,Young Guns,101
127,Basic Instinct,101
980,Mimic,101
1300,"Sex, Lies, and Videotape",101


In [ ]:
avg_rating.head()

,movie title,Avg_rating
0,'Til There Was You,2.333333
1,1-900,2.600000
2,101 Dalmatians,2.908257
3,12 Angry Men,4.344000
4,187,3.024390


In [ ]:
movie_count100.head()

,movie title,Rating Counts
1393,Star Wars,583
332,Contact,509
497,Fargo,508
1232,Return of the Jedi,507
858,Liar Liar,485


In [ ]:
top_movie_by_avg = avg_rating.merge(movie_count100, on='movie title', how='inner')
top_movie_by_avg

,movie title,Avg_rating,Rating Counts
0,101 Dalmatians,2.908257,109
1,12 Angry Men,4.344000,125
2,2001: A Space Odyssey,3.969112,259
3,Absolute Power,3.370079,127
4,"Abyss, The",3.589404,151
...,...,...,...
329,Willy Wonka and the Chocolate Factory,3.631902,326
330,"Wizard of Oz, The",4.077236,246
331,"Wrong Trousers, The",4.466102,118
332,Young Frankenstein,3.945000,200


In [ ]:
top_movie_by_avg.sort_values('Avg_rating', ascending=False)

,movie title,Avg_rating,Rating Counts
63,"Close Shave, A",4.491071,112
260,Schindler's List,4.466443,298
331,"Wrong Trousers, The",4.466102,118
54,Casablanca,4.456790,243
269,"Shawshank Redemption, The",4.445230,283
...,...,...,...
281,Spawn,2.615385,143
101,Event Horizon,2.574803,127
74,Crash,2.546875,128
168,Jungle2Jungle,2.439394,132


In [ ]:
df_merge_all = df_merge.merge(user, on = 'user id', how = 'inner')
df_merge_all.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,War,Western,Number of Genres,user id,rating,timestamp,age,gender,occupation,zip code
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,6,308,4,887736532,60,M,retired,95076
1,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,6,287,5,875334088,21,M,salesman,31211
2,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,6,148,4,877019411,33,M,engineer,97006
3,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,6,280,4,891700426,30,F,librarian,22903
4,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,6,66,3,883601324,23,M,student,80521


In [ ]:
df_merge_all['zip code'].value_counts()

,count
zip code,
55414,1103
20009,878
10019,850
22902,832
61820,817
...,...
60302,20
93117,20
38866,20
